Feature/check network state
digital-voting-pass/digital-voting-pass-app pull request #111
Opened 2017-06-09 12:30 UTC by jonathanraes

Closes #103 
Checks network state in SplashActivity

2017-06-09 15:06 UTC, landgenoot commented
Add snackbar with shortcut to connection settings.

2017-06-12 08:59 UTC, wkmeijer requested changes
When you re-enable the network and go back to the app too fast the toast that says "Please enable network connection" is shown, even though the network connection was just enabled.

When the network connection is disabled in e.g. mainactivity no error is given, even though it should still update the blockchain.

2017-06-13 13:25 UTC, wkmeijer requested changes
Snackbar is an improvement. Handling lost network connection in the rest of the app will be done at a later point. 

Please also run 'optimize imports' on the project one last time.

2017-06-13 13:25 UTC, wkmeijer commented on app/src/main/res/values/strings.xml
> +    <string name="go_network_settings">Settings</string>
Please change this to "WIFI SETTINGS" so it's more clear where the button will take the users.

2017-06-14 13:32 UTC, jonathanraes commented
waiting for #139 for updated translations,

2017-06-21 08:14 UTC, wkmeijer approved these changes

2017-06-21 08:15 UTC, merged