Feature/23 submit transaction
digital-voting-pass/digital-voting-pass-app pull request #112
Opened 2017-06-09 13:02 UTC by landgenoot

2017-06-09 13:24 UTC, jonathanraes commented on app/build.gradle
> +    testCompile 'org.mockito:mockito-android:2.7.22'
duplicate dependency, also line 52

2017-06-09 13:28 UTC, klikooo commented on app/src/main/java/com/digitalvotingpass/blockchain/ConfirmationTracker.java
> +public class ConfirmationTracker extends DownloadProgressTracker {
Is this class used?

2017-06-09 13:39 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/blockchain/BlockChain.java
> +    public byte[] getSpendUtxoTransaction(TransactionOutput utxo, Address destination, PassportConnection pcon) {
This creates a new signed transaction, right? Method name is kind of unclear

2017-06-09 13:42 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/blockchain/ConfirmationTracker.java
> +public class ConfirmationTracker extends DownloadProgressTracker {
Unused class

2017-06-09 14:10 UTC, jonathanraes requested changes
great, but listening for rejects is still good to do I think, since it can still happen, also timeout for confirmation

2017-06-09 14:51 UTC, landgenoot commented on app/src/main/java/com/digitalvotingpass/blockchain/ConfirmationTracker.java
> +public class ConfirmationTracker extends DownloadProgressTracker {
Solved.

2017-06-09 14:52 UTC, landgenoot commented on app/src/main/java/com/digitalvotingpass/blockchain/BlockChain.java
> +    public byte[] getSpendUtxoTransaction(TransactionOutput utxo, Address destination, PassportConnection pcon) {
Renamed it to `utxoToSignedTransaction()`

2017-06-09 14:53 UTC, landgenoot commented on app/src/main/java/com/digitalvotingpass/blockchain/ConfirmationTracker.java
> +public class ConfirmationTracker extends DownloadProgressTracker {
Solved

2017-06-09 14:53 UTC, landgenoot commented on app/build.gradle
> +    testCompile 'org.mockito:mockito-android:2.7.22'
Solved

2017-06-10 10:51 UTC, jonathanraes approved these changes

2017-06-10 12:10 UTC, merged