Feature/125 test build tx
digital-voting-pass/digital-voting-pass-app pull request #128
Opened 2017-06-12 19:42 UTC by klikooo

2017-06-13 12:04 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/passportconnection/PassportConActivity.java
> +                progressView.setImageResource(R.drawable.nfc_icon_3);
why set icon 2 before icon 3? (line 171)

2017-06-13 13:54 UTC, wkmeijer requested changes
Nice tests, I have 2 minor comments.

2017-06-13 13:54 UTC, wkmeijer commented on app/src/test/java/com/digitalvotingpass/passportconnection/PassportTransactionFormatterTest.java
> +        when(to.getScriptBytes()).thenReturn(new BigInteger("76a914010966776006953d5567439e5e39f86a0d273bee88ac", 16).toByteArray());
This could introduce the bug where a '0' byte is added, it's better to use` Util.hexStringtoByteArray()`. Same goes for the other occurrences of using biginteger to parse a byte arrray.

2017-06-13 13:54 UTC, wkmeijer commented on app/src/test/java/com/digitalvotingpass/passportconnection/PassportTransactionFormatterTest.java
> +    private MainNetParams mp = MultiChainParams.get(
This is never used.

2017-06-14 13:30 UTC, wkmeijer approved these changes

2017-06-14 13:30 UTC, merged