40_refactor_camera_class
digital-voting-pass/digital-voting-pass-app pull request #133
Opened 2017-06-13 13:05 UTC by wkmeijer

Split camera2basic fragment into three classes.

2017-06-13 15:06 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/camera/Camera2BasicFragment.java
> +public class Camera2BasicFragment extends Fragment implements FragmentCompat.OnRequestPermissionsResultCallback {
maybe a rename of Camera2BasicFragment class is a good idea

2017-06-13 15:07 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/camera/Camera2BasicFragment.java
>          ORIENTATIONS.append(Surface.ROTATION_270, 180);
I believe this is unused

2017-06-13 15:28 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/camera/CameraHandler.java
> +    private boolean needSwappedDimensions(CameraCharacteristics characteristics) {
The activity param doesnt exist anymore. Also this method can probably also be moved to CameraSupport

2017-06-13 15:32 UTC, jonathanraes requested changes
Greatly reduces Camera2BasicFragment in sie which is awesome.
I think however in order to please SIG we can still break some of the camera related methods into multiple shorter ones.
Also kind of unsure about CameraSupport, since all its methods are only used once and it doenst seem to have a clear single responsibility

2017-06-14 13:26 UTC, wkmeijer commented on app/src/main/java/com/digitalvotingpass/camera/Camera2BasicFragment.java
>          ORIENTATIONS.append(Surface.ROTATION_270, 180);
You are correct

2017-06-14 13:26 UTC, wkmeijer commented on app/src/main/java/com/digitalvotingpass/camera/Camera2BasicFragment.java
> +public class Camera2BasicFragment extends Fragment implements FragmentCompat.OnRequestPermissionsResultCallback {
Renamed to CameraFragment

2017-06-14 13:37 UTC, klikooo commented on app/src/main/java/com/digitalvotingpass/camera/CameraFragment.java
> +            returnIntent.putExtra("docData", data);
we have a final static string for this: DocumentData.identifier

2017-06-14 13:42 UTC, wkmeijer commented on app/src/main/java/com/digitalvotingpass/camera/CameraFragment.java
> +            returnIntent.putExtra("docData", data);
fixed

2017-06-16 14:57 UTC, jonathanraes approved these changes

2017-06-21 11:47 UTC, merged