show number of passes instead of 0 after sending transaction
digital-voting-pass/digital-voting-pass-app pull request #135
Opened 2017-06-13 13:10 UTC by jonathanraes

not tested, will test at home with other phone.

2017-06-13 14:36 UTC, wkmeijer requested changes
Snackbar with two lines flows under the card, margin for the card could be increased.
It is not very clear that 'has right to' changed to 'please hand out' in the card view. Maybe the look of that sentence could also be changed.

2017-06-13 14:36 UTC, wkmeijer commented on app/src/main/java/com/digitalvotingpass/digitalvotingpass/ResultActivity.java
>                          textVotingPasses.setText(R.string.voting_passes);
Set this text to 'ballot papers'

2017-06-14 13:33 UTC, jonathanraes commented
wait for #139 and update translations

2017-06-16 14:55 UTC, jonathanraes commented
processed comments, please check if the card view now has enough margin for 2 line snackbar

2017-06-21 12:55 UTC, wkmeijer approved these changes

2017-06-21 13:01 UTC, merged