Feature/33 jmrtd ocr coupling closes #33
digital-voting-pass/digital-voting-pass-app pull request #43
Opened 2017-05-19 10:53 UTC by wkmeijer

In order to scan the passport first the MRZ has to be scanned by using OCR, if this fails a manual input can be used. The document details get send to the passport connection activity which opens a connection with the passport.

2017-05-19 13:38 UTC, jonathanraes approved these changes

2017-05-19 13:39 UTC, jonathanraes commented on app/src/main/AndroidManifest.xml
>              </intent-filter>
I think this whole intent-filter can be deleted

2017-05-19 13:44 UTC, wkmeijer commented on app/src/main/AndroidManifest.xml
>              </intent-filter>
agreed

2017-05-19 14:23 UTC, klikooo commented on app/src/main/java/com/digitalvotingpass/digitalvotingpass/MainActivity.java
> +                    documentData = (HashMap<String, String>) data.getSerializableExtra("result");
The cases GET_MANUAL_DOC_INFO and GET_DOC_INFO both have the same code in them.

2017-05-19 14:26 UTC, klikooo requested changes
Please fix the above comment

2017-05-22 10:48 UTC, klikooo approved these changes

2017-05-22 10:48 UTC, merged