feature/generate_mc_address
digital-voting-pass/digital-voting-pass-app pull request #72
Opened 2017-05-31 12:55 UTC by jonathanraes

Get the MultiChain addresses corresponding to epassport's public keys

2017-06-01 09:50 UTC, klikooo requested changes

2017-06-01 09:50 UTC, klikooo commented on app/src/main/java/com/digitalvotingpass/passportconnection/PassportConnection.java
> +
Remove these  enters/tabs

2017-06-01 09:50 UTC, klikooo commented on app/src/main/java/com/digitalvotingpass/utilities/AddressGenerator.java
> +        //Step 3
Where are step 1 and 2?

2017-06-01 09:50 UTC, klikooo commented on app/src/test/java/com/digitalvotingpass/passportconnection/PassportConnectionTest.java
> +import com.digitalvotingpass.utilities.AddressGenerator;
Are these imports needed?

2017-06-01 09:50 UTC, klikooo commented on app/src/main/java/com/digitalvotingpass/utilities/AddressGenerator.java
> +public class AddressGenerator {
Is it possible to apply the factory pattern here?

2017-06-01 09:50 UTC, klikooo commented on app/src/main/java/com/digitalvotingpass/utilities/AddressGenerator.java
> +        return getPublicAddress(pubKey.getEncoded());
This will probably not work since `pubKey.getEncoded()` returns a ASN1 format

2017-06-02 15:19 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/utilities/AddressGenerator.java
> +        //Step 3
Step 1: Start with a raw private ECDSA key
Step 2: Take the corresponding public key generated with it, which can be in compressed or uncompressed format. The uncompressed version contains 65 bytes, consisting of 0x04, 32 bytes for the X coordinate and 32 bytes for the Y coordinate. The compressed version contains 33 bytes, consisting of 0x02 (Y is even) or 0x03 (Y is odd), followed by 32 bytes for the X coordinate. Below is a compressed example:

I dont think any code is required for steps 1 and 2

2017-06-05 13:23 UTC, wkmeijer approved these changes
Hard to know for sure if it will actually work with the blockchain but it looks like it should. Nice that you made it very clear which steps are taken in order to generate the multichain address and that you added test cases.

2017-06-05 14:54 UTC, klikooo approved these changes

2017-06-05 14:58 UTC, merged