Feature/67 statusbar theme
digital-voting-pass/digital-voting-pass-app pull request #73
Opened 2017-06-01 09:08 UTC by jonathanraes

Closes #67

2017-06-01 10:29 UTC, wkmeijer requested changes
Looks good everywhere except in the TransactionHistoryActivity. The actionicon causes the appbar to not flow under the status bar.

2017-06-02 08:09 UTC, jonathanraes commented
Should now be  fixed, also enables force portrait mode in splashactivity

2017-06-02 10:37 UTC, wkmeijer commented
Latest commit fixed the issues.

2017-06-02 10:37 UTC, wkmeijer approved these changes

2017-06-02 13:23 UTC, merged