Feature/70 election shared preferences
digital-voting-pass/digital-voting-pass-app pull request #75
Opened 2017-06-01 09:57 UTC by wkmeijer

The election choice is now saved in shared preferences which makes it accessible to all activities. Furthermore it is now possible to edit the election choice from the mainactivity. The electionchoice activity is only loaded on start-up when there is no election choice saved.

2017-06-01 12:41 UTC, klikooo requested changes
Looks good and works! Although I want to see one minor change

2017-06-01 12:41 UTC, klikooo commented on app/src/main/java/com/digitalvotingpass/electionchoice/ElectionChoiceActivity.java
> +                SharedPreferences sharedPrefs = getSharedPreferences(getString(R.string.shared_preferences_file), Context.MODE_PRIVATE);
Can you make this a separate function?

2017-06-02 08:21 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/digitalvotingpass/MainActivity.java
> +                finish();
Why call finish? is it needed?

2017-06-02 08:25 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/digitalvotingpass/MainActivity.java
> +                finish();
I see why its needed now, for the back behaviour, is it not better to remove the ElectionChoiceactivity from the back stack?

2017-06-02 08:27 UTC, jonathanraes commented on app/src/main/java/com/digitalvotingpass/electionchoice/ElectionChoiceActivity.java
> +                SharedPreferences sharedPrefs = getSharedPreferences(getString(R.string.shared_preferences_file), Context.MODE_PRIVATE);
I agree accessing the preferences may be nice in a seperate class even

2017-06-02 09:54 UTC, wkmeijer commented on app/src/main/java/com/digitalvotingpass/digitalvotingpass/MainActivity.java
> +                finish();
Well, the problem is that the MainActivity needs to be reloaded with the new election data. I could start electionchoice with `startActivityForResult` and reload the data when electionchoice finishes. That is a more elegant solution.

2017-06-02 09:57 UTC, wkmeijer commented on app/src/main/java/com/digitalvotingpass/electionchoice/ElectionChoiceActivity.java
> +                SharedPreferences sharedPrefs = getSharedPreferences(getString(R.string.shared_preferences_file), Context.MODE_PRIVATE);
A separate class seems a bit much for these few lines of code. I think it's no problem for these lines to be in the `onItemClick` method since the total lines of the method is not very high. But if you both agree that a separate method is better, I'll do that.

2017-06-02 11:04 UTC, klikooo approved these changes

2017-06-02 11:05 UTC, klikooo commented
Nice! Works like a charm

2017-06-02 11:35 UTC, merged